/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controllers.ControllersMateriaPrima;
import Controllers.ControllersProveedor;
import static Vista.Inicio.principal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A
 */
public class MateriaPrima extends javax.swing.JInternalFrame {
    private ArrayList<ControllersMateriaPrima> listaMateriaPrima = new ArrayList<>();
    private DefaultTableModel modeloTabla;

public MateriaPrima(String nombre, String codigo, String unidad, String medida, int cantidad, String tipo, String proveedor, String fechaingreso) {
        
}   
        
    public MateriaPrima(){
        
        super("Materia Prima", true, true, true, true);
        initComponents();
        
        

cargarProveedores();


        
        filtroProveedormp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Filtrar por Proveedor", "Plasticos Reunidos", "Petroquimica del Norte", "Industrias Resiplast", "Resinas del Bajio"
        }));
        
        filtroTipomp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Filtrar por Tipo", "Termoestables", "Termoplasticos"
        }));
       
        unitmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Liquido", "Laminas", "Granulos", "Pellets", "Pasta", "Polvo", "Preformas"
        }));
        
        typemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
             "Termoestables", "Termoplasticos"
        }));
        
        
       
        modeloTabla = new DefaultTableModel();
        modeloTabla.setColumnIdentifiers(new String[]{"Nombre", "Codigo", "Unidad", "Medida", "Cantidad", "Tipo", "Proveedor"});
        existenciasmp.setModel(modeloTabla);

    }
    
    public void listaMateriaPrima() {
        modeloTabla.setRowCount(0);
        
        for (ControllersMateriaPrima m : listaMateriaPrima) {
            modeloTabla.addRow(m.toRow());
        }
    }

    
    
   
    private void Filtros(){
        String proveedorFiltro = filtroProveedormp.getSelectedItem().toString();
        String tipoFiltro = filtroTipomp.getSelectedItem().toString();
        
        modeloTabla.setRowCount(0);
        
        for (ControllersMateriaPrima m : listaMateriaPrima) {
            boolean coincideProveedor = proveedorFiltro.equals("Filtrar por proveedor") || m.getProveedor().equals(proveedorFiltro);
            boolean coincideTipo = tipoFiltro.equals("Filtarar por Tipo") || m.getTipo().equals(tipoFiltro);
            
            if (coincideProveedor && coincideTipo) {
                modeloTabla.addRow(m.toRow());
            }
        }
    }
    
    private void cargarProveedores() {
        ControllersProveedor proveedorDAO = new ControllersProveedor();
        List<ControllersProveedor> listProveedores = proveedorDAO.listarProveedor();
        
        System.out.println("Proveedores encontrados" +listProveedores.size());
        
        provmp.removeAllItems();
        
        provmp.addItem("Seleccionar proveedor");
        
        for (ControllersProveedor p : listProveedores) {
            provmp.addItem(p.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel115 = new javax.swing.JLabel();
        codemp = new javax.swing.JTextField();
        namemp = new javax.swing.JTextField();
        cantmp = new javax.swing.JTextField();
        provmp = new javax.swing.JComboBox<>();
        medmp = new javax.swing.JComboBox<>();
        unitmp = new javax.swing.JComboBox<>();
        typemp = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        existenciasmp = new javax.swing.JTable();
        filtroProveedormp = new javax.swing.JComboBox<>();
        filtroTipomp = new javax.swing.JComboBox<>();
        Tdodomp = new javax.swing.JButton();
        datemp = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        entermp = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(46, 54, 79));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel17.setText("M a t e r i a   P r i m a");

        jLabel18.setText(" ");

        jPanel18.setBackground(new java.awt.Color(125, 125, 157));

        jLabel115.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel115.setText("Nombre:");

        codemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codempjTextField1ActionPerformed(evt);
            }
        });

        namemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namempjTextField3ActionPerformed(evt);
            }
        });

        provmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Plasticos polinesios", "Fernan el plasticrack", "Plasticos peligrosos", "Fentanilo PLastico" }));

        unitmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitmpActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(10, 12, 91));

        existenciasmp.setBackground(new java.awt.Color(204, 204, 204));
        existenciasmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Codigo", "Unidad", "Medida", "Cantidad", "Tipo", "Proveedor", "Fecha ing."
            }
        ));
        jScrollPane1.setViewportView(existenciasmp);

        filtroProveedormp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroProveedormpActionPerformed(evt);
            }
        });

        filtroTipomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroTipompActionPerformed(evt);
            }
        });

        Tdodomp.setText("Todo");
        Tdodomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TdodompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(filtroProveedormp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(filtroTipomp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tdodomp, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtroProveedormp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroTipomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tdodomp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        datemp.setText("        /           /");

        jTextField1.setText("ID empleado");

        jLabel124.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel124.setText("Codigo: ");

        jLabel125.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel125.setText("Unidad: ");

        jLabel126.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel126.setText("Medida: ");

        jLabel127.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel127.setText("Cantidad: ");

        jLabel128.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel128.setText("Tipo: ");

        jLabel129.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel129.setText("Proveedor: ");

        jLabel130.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel130.setText("Solicitó: ");

        jLabel131.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel131.setText("Fecha Ingreso: ");

        entermp.setBackground(new java.awt.Color(121, 145, 168));
        entermp.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        entermp.setForeground(new java.awt.Color(7, 16, 24));
        entermp.setText("Entrada");
        entermp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entermpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel124, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel115, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel129, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel130, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel131, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel125, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel126, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel127, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel128, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typemp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantmp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medmp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitmp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provmp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(namemp)
                        .addComponent(codemp)
                        .addComponent(datemp, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addComponent(jTextField1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(entermp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel115)
                            .addComponent(namemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel124))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unitmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel125))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel126))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel127))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel128))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(provmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel129))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel131))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel130)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entermp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel18)
                .addGap(30, 30, 30)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codempjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codempjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codempjTextField1ActionPerformed

    private void namempjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namempjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namempjTextField3ActionPerformed

    private void unitmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitmpActionPerformed
        String seleccion = unitmp.getSelectedItem().toString();
        medmp.removeAllItems();
        switch (seleccion) {
            case "Liquido":
            medmp.addItem("Litros");
            break;
            case "Laminas":
            medmp.addItem("Lamina (10x10)");
            break;
            case "Granulos":
            case "Pellets":
            case "Pasta":
            case "Polvo":
            case "Preformas":
            medmp.addItem("Kilos");
            break;
        }
    }//GEN-LAST:event_unitmpActionPerformed

    private void filtroProveedormpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroProveedormpActionPerformed
        Filtros();
    }//GEN-LAST:event_filtroProveedormpActionPerformed

    private void filtroTipompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroTipompActionPerformed
        Filtros();
    }//GEN-LAST:event_filtroTipompActionPerformed

    private void TdodompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdodompActionPerformed
        filtroProveedormp.setSelectedItem("Filtrar por Proveedor");
        filtroTipomp.setSelectedItem("Filtrar por Tipo");
        Filtros();
    }//GEN-LAST:event_TdodompActionPerformed

    private void entermpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entermpActionPerformed

        NuevaVenta v = new NuevaVenta();
        principal.add(v);
        v.pack();
        v.setVisible(true);
    }//GEN-LAST:event_entermpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tdodomp;
    private javax.swing.JTextField cantmp;
    private javax.swing.JTextField codemp;
    private javax.swing.JTextField datemp;
    private javax.swing.JButton entermp;
    private javax.swing.JTable existenciasmp;
    private javax.swing.JComboBox<String> filtroProveedormp;
    private javax.swing.JComboBox<String> filtroTipomp;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> medmp;
    private javax.swing.JTextField namemp;
    private javax.swing.JComboBox<String> provmp;
    private javax.swing.JComboBox<String> typemp;
    private javax.swing.JComboBox<String> unitmp;
    // End of variables declaration//GEN-END:variables

    
}
